### ISSUE TITLE
Setup "use the instance configuration to talk to S3"

### ISSUE THREAD

**Issue by Lunteer** [tc-mccarthy/tcs3#38]
Hey. Thanks for the plugin and all the help.

Not an issue but lack of direction/documentation. 

1) Not a hard core programmer but can figure things out. How can I setup my EC2 instance to talk with s3 without having the plugin store my AWS IAM Keys? I did create the IAM user but would prefer not having the keys stored in the DB open. (Side Question - Anyway you can secure it in the DB encrypted?)

2) I added the keys and believed everything is setup correctly but nothing synced and no error messages. 2a) How can I tell if things are working or not? 2b) if not working, where would the errors be?
 
Thanks for the help.

**Comment by tc-mccarthy** [comment]
Hey @Lunteer, 

1. So with regard to number 1. there are instructions for the AWS CLI that allow you to set an 'instance' configuration if you're running an EC2 instance. If it's set, any communication over an AWS SDK will inherit that configuration unless otherwise specified. There are more details available [here](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/credentials.html#environment-credentials)

2. There is no 'sync' operation that happens immediately. You can opt to sync using the button provided or you can manually copy your uploads folder from your server to S3 using tools like the AWS CLI, cyberduck, etc. You can tell if the plugin is working by uploading something new, going in to the media library and clicking on your upload. If it shows up and its URL matches the one you provided for your S3 bucket then your configuration is all set!

**Comment by Lunteer** [comment]
@tc-mccarthy Thanks for all the help. Figured out how to sync!

We were looking into automating the sync so when a user uploads a media file it will become available right away. This is more scalable as we have many clients using our system.

Wanted to know why you have not implemented this yet (I am assuming just never needed it). Have you put though into how you would do it? using the wp-cron.php or something on the server side in a regular cron.

We would love to contribute to this project so looking for your input.
Thanks!!

**Comment by Lunteer** [comment]
And for those who are looking for a simple solution to syncing almost on demand. We setup a cron job on the server to sync once a minute. Here are the steps.

1. Setup a bash file with the simple something like`#!/bin/bash
aws s3 sync /var/www/wp-content/uploads/ s3://bucket-name/uploads/`
2. type crontab -e (opens a vi editor, which is a bit tricky to use)
3. type 'i' then add '* * * * * /path/to/the/bash/file' then esc and SHIFT +Z +Z
4. you should get a confirmation in the command line that a file has been created.
.
We even went so far as to create a second s3 bucket just to backup everything without public access. We added a second line to the bash file to sync that bucket also

**Comment by tc-mccarthy** [comment]
I’m a bit confused. The whole purpose of this plugin is that it pushes media directly to the S3 bucket at the time of upload.

If this isn’t happening for you, you should check your configuration...

TC McCarthy
631.320.8272

**Comment by Lunteer** [comment]
Sorry for the confusion. Based on your above answer of #2 it sounded like it does not upload to S3 right away. I think the confusion was that it does not run a sync command for previous files. Is that correct?

And it is not uploading right away to s3 but everything else seems to be working well (URL rewrites to the Cloudfront, etc.).

**Comment by tc-mccarthy** [comment]
If you’re not seeing an upload then you should check your local path configuration. Read your web server logs during an upload to see where the process is failing.

With regard to syncing previous files, no that is not a feature that is automatically enabled with this plug-in. There is a button in the sync tab of the configuration page that will do this, but it would be unwise for me to automate that since there are many websites out there that take on this plug-in after uploading thousands and thousands of files. PHP is a great language for many things, but asking it to upload thousands upon thousands of uploaded files to S3 is not the best use of resources when you have alternate solutions like the AWS-CLI.

Users who take on S3 as a means for upload storage tend to be more savvy and don’t need developers like me who don’t know much about their particular scenario making decisions for them.

I hope I’ve clarified your questions! Let me know if there’s anything else.

TC McCarthy
631.320.8272

**Comment by Lunteer** [comment]
Thanks for all the clarification. Will need to run some upload test to see where there is an issue.

I am trying to play with the big boys so am learning and making plenty of mistakes.

Thanks for your patience and help!!

**Comment by tc-mccarthy** [comment]
Make mistakes, my friend.

It’s the best way to learn.

TC McCarthy
631.320.8272

**Comment by tc-mccarthy** [comment]
@Lunteer "failure to initiate multipart upload" means your server isn't able to successfully establish a connection to S3 to upload the files. The first example you sent is because your access key id field is empty (which I think you're expecting). The second error appears to be because the IAM keys you're using are missing a permission. I have always found IAM permissions to be frustrating -- please follow (https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html)[this guide] to ensure you have all of the needed permissions for a multipart upload. If you still can't get it to work, create some temporary IAM keys that have every permission possible and an open bucket policy and see if that resolves the issue. If it does, then you know it's permissions and that you're looking in the right place. Otherwise, you'll likely have a new error in the log that you can work from.

**Comment by Lunteer** [comment]
@tc-mccarthy Thanks for the direction. It was a permissions issue and it took a hell of a long time to figure out which permissions were needed. It was not just the multi* one but many others. Rather annoying.

So just in case someone else needs it, here are the permissions I found worked for our IAM user to upload from ec2 to s3.
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucketMultipartUploads",
                "s3:AbortMultipartUpload",
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:DeleteBucket",
                "s3:PutObjectAcl",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket",
                "arn:aws:s3:::*/*"
            ]
        }
    ]
}`

I also want to mention that I need to have the credentials on the authentication page. Have not gotten it to work with ec2 to s3 but thinking about it do I need to attach an IAM?
